spring.application.name=gamehub-backend
spring.datasource.url=jdbc:mysql://localhost:3306/gamehub
spring.datasource.username=gamehub
spring.datasource.password=Frifri26082005*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true